{
 "title": "Node Problem Detector",
 "description": "https://github.com/kubernetes/node-problem-detector",
 "tags": [
  "infra",
  "node"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "problem_counter_reason",
    "query": {
     "query": "label_values(problem_counter,reason)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(problem_counter,node)"
    }
   },
   {
    "name": "problem_type",
    "query": {
     "query": "label_values(problem_gauge,type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Problem affects a node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": " sum(problem_gauge) by (node)", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Problem rates by node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(problem_counter[5m])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Problem rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    { "expr": "sum(rate(problem_counter[5m]))", "legendFormat": "total" }
   ]
  },
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Problem Type - $problem_type",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "repeat": "problem_type",
   "targets": [
    {
     "expr": "sum(problem_gauge{type=~\"$problem_type\"})",
     "legendFormat": "$problem_type"
    }
   ]
  },
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Problem rates - $problem_counter_reason",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "repeat": "problem_counter_reason",
   "targets": [
    {
     "expr": "sum(rate(problem_counter{reason=~\"$problem_counter_reason\"}[5m]))",
     "legendFormat": "$problem_counter_reason"
    }
   ]
  }
 ]
}